### ISSUE TITLE
Reference to sub-clause 5.3 in OWS Common

### ISSUE THREAD

**Issue by morpl** [opengeospatial/templates#17]
In standard_template/standard/clause_4_terms_and_definitions.adoc there is a reference to Sub-clause 5.3 of OGC 06-121r8.

When reading "OGC API - Common" it struck me as a little odd to have a reference to the current OWS Common for other reasons that history and comparison.

Perhaps the contents of sub-clause 5.3 should be spelled out in the template (making it self-contained)?

Or perhaps there could be a reference to the ISO/IEC Directives?
https://www.iso.org/sites/directives/current/part2/index.xhtml

Or perhaps the contents of sub-clause 5.3 should be spelled out in another OGC document than OWS Common?

(Moreover, the current version 2.0.0 of OGC Web Service Common Implementation Specification to be found on www.ogc.org actually has a newer revison than the reference in the template: document# 06-121r9. But I would suggest a template without the reference to OWS Common.)

**Comment by ogcscotts** [comment]
@morpl Good comment - a reference to a persistent terminology rule would be better. I suggest that we create a Policy Directive in OGC that states the same thing as in Section 5.3 of OWS Common and more explicitly states that the "equivalent phrases" used in the ISO/IEC directives are not permitted.

**Comment by ghobona** [comment]
The reference to OWS Common in the Terms and Definitions section has been removed since changing the template to the metanorma template.

The published OGC API - Common - Part 1: Core document is [here](https://docs.ogc.org/is/19-072/19-072.html#_d09acd86-2c83-4ead-95a9-54b37ff7c2d1).
