### ISSUE TITLE
Make use of the "keyword" attribute

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/templates#18]
I would like suggest to add the "keywords" attribute to the templates, and perhaps the "description" keyword as well.

From http://asciidoc.org/userguide.html#X88 :

> The keywords and description attributes set the correspondingly named HTML meta tag contents; the title attribute sets the HTML title tag contents. Their principle use is for SEO (Search Engine Optimisation).

See an example in https://raw.githubusercontent.com/heidivanparys/discussion_paper_dataset/master/dp.adoc .

```
= On the definition of “dataset”
:title: On the definition of “dataset”
:titletext: {Title}
:keywords: dataset,data set,ogcdoc,OGC document
:description: The concept of “dataset” is a key concept in many domains. This document tries to come to a better understanding of it.
```

```
<meta name="description" content="The concept of “dataset” is a key concept in many domains. This document tries to come to a better understanding of it.">
<meta name="keywords" content="dataset,data set,ogcdoc,OGC document">
<title>On the definition of “dataset”</title>
```

**Comment by ghobona** [comment]
Thanks @heidivanparys . The issue has been re-logged in the metanorma-ogc repo as it will require enhancement of metanorma.
