### ISSUE TITLE
Collapsible license?

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/templates#28]
At the last OGC meeting, a remark was made that developers first have to read through a lot of text, especially the license, before they come to the actual contents.

Just an idea: Asciidoctor has a "collapsible" feature. See https://github.com/heidivanparys/templates/commit/7790a032256f7ea134642a77a5f0487ded672c58 and the links in the contents for the syntax.

Collapsed:

![image](https://user-images.githubusercontent.com/11427611/122746847-b772b580-d28a-11eb-8c8e-d8163ca97e5f.png)

Expanded:

![image](https://user-images.githubusercontent.com/11427611/122746905-c5283b00-d28a-11eb-81b9-1df4d56d4382.png)

**Comment by ogcscotts** [comment]
@heidivanparys thanks! This is a good solution. We are also considering moving boilerplate text off to linked content on a static web page for licensing. We can test each of these and see which is most appealing to the Doc Team.

**Comment by ghobona** [comment]
The license agreement is now linked to.

An example can be seen in [OGC 19-086r6](https://docs.ogc.org/is/19-086r6/19-086r6.html#_15067213-c07b-cba0-7e18-395ab2e00ab3).
