### ISSUE TITLE
metanorma docker container should be metanorma/metanorma

### ISSUE THREAD

**Issue by ogcscotts** [opengeospatial/templates#35]
the "mn" container seems to use the old cover page and OGC logo. Instructions for use of Docker should reference the "metanorma/metanorma" container.

**Comment by ghobona** [comment]
Metanorma automatically changes between the old and new OGC logos depending on the publication date of the document. The cutoff date is [2021-11-08](https://github.com/metanorma/metanorma-ogc/blob/main/lib/isodoc/ogc/metadata.rb#L139).

The metanorma/mn container supports this feature.

**Comment by ghobona** [comment]
@ronaldtse has just explained to me that the recommended production image is metanorma/metanorma. The “mn” image is an edge build intended for development. 

I will update the OGC templates documentation to reference metanorma/metanorma instead of metanorma/mn.
