### ISSUE TITLE
Update Editorial Guidance with recommendation for inline references in Engineering Reports

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/templates#39]
The COSI team has requested that the Editorial Guidance be updated to recommend use of inline references in Engineering Reports.

**Comment by ogcscotts** [comment]
Approved by DocTeam 23 April. Will be included in new Engineering Report template heading to TC approval vote.

**Comment by ogcscotts** [comment]
TC has approved Engineering Report template.
