### ISSUE TITLE
Template for standards does not follow metanorma in the requirements and requirements classes templates.

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/templates#51]
While the readme.md in:

https://github.com/opengeospatial/templates/tree/master/standard

clearly explains that we should use metanorma for standards, the templates for requirements and requirements classes are not using the metanorma.org instructions (https://www.metanorma.org/author/topics/blocks/requirements-modspec/) and generate confusion in editors. See:
https://github.com/opengeospatial/templates/tree/master/standard/template/requirements

Please update them. You can use the work that Gobe did in transforming the OGC API maps to metanorma. Two examples here:
* https://raw.githubusercontent.com/opengeospatial/ogcapi-maps/refs/heads/master/core/standard/requirements/requirements_class_core.adoc
* https://raw.githubusercontent.com/opengeospatial/ogcapi-maps/refs/heads/master/core/standard/requirements/core/REQ_map-op.adoc

**Comment by ghobona** [comment]
@joanma747 Thanks for reporting the issue. 

We will update the templates to the use definitions list syntax.
